# Script to build and publish a Reloaded Mod.
# by Sewer56

# Produces: 
#   - Build to Upload to GameBanana
#   - Build to Upload to GitHub
#   - Build to Upload to NuGet
#   - Changelog

# When pushing a tag
#   - Upload to GitHub Releases
#   - Upload to Reloaded NuGet Repository (if GitHub Secret RELOADED_NUGET_KEY is specified) 

name: Build and Publish Reloaded Mod

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PUBLISH_PATH_GLOB: ./Publish/ToUpload/**/Generic/*
  RELOADEDIIMODS: .

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Setup .NET Core SDK (5.0/6.0/7.0)
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          7.0.x

    - name: Build
      run: ./PublishAll.ps1 -ChangelogPath "$env:PUBLISH_CHANGELOG_PATH"
      
    - name: Upload GitHub Release Artifact
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: GitHub Release
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          ${{ env.PUBLISH_PATH }}

    - name: Upload Latest Prerelease to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        # Overwrite the previous prerelease tag
        prerelease: true
        tag_name: prerelease
        # Path to load note-worthy description of changes in release from
        body: Latest development version
        # Newline-delimited list of path globs for asset files to upload
        files: |
          ${{ env.PUBLISH_PATH_GLOB }}
          ./mrdx_reloaded.r2pack